/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package flyfolio.api

import io.javalin.Javalin

fun main() {
    val App = Javalin.create(/*config*/)
        .get("/") { ctx -> ctx.result("Hello World") }
        .start(7070)
}
